apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-dep-wp
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep-wp
  strategy: {}
  template:
    metadata:
      labels:
        app: my-dep-wp
    spec:
      containers:
      - name: wp
        image: wordpress:4.8-apache
        ports:
        - containerPort: 80
          name: wp
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql-db
        # - name: WORDPRESS_DB_USER
        #   value: root  
        # - name: WORDPRESS_DB_NAME
        #   value: wp-db
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-sql-password
              key: pass
        resources: {}
        volumeMounts:
        - mountPath: "/var/www/html"
          name: mypd
        # - mountPath: "/var/www/html/wp-config.php"
        #   name: config-vol
      volumes:
        # - name: config-vol
        #   configMap:
        #     name: my-config
        #     items:
        #     - key: wp-config.php
        #       path: keys
        - name: mypd
          persistentVolumeClaim:
            claimName: myclaim-wp
status: {}