apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wp
spec:
  storageClassName: local-storage
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wp"