apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim-wp
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage